$(document).ready(function() 
{
	$(".header").click(function(){
		if($(this).height() == 480)
		{
			$(this).animate({
				height:"420px"
			});
			$("#text_frame").animate({
				height:"60"
			});
			$("#text").animate({
				opacity:"1"
			});
		}
		else
		{
			$(this).animate({
				height:"480"
			});
			$("#text_frame").animate({
				height:"0"
			});
			$("#text").animate({
				opacity:"0"
			});
		}
		
	    });
});