$(document).ready(function() 
{
	$(".header").click(function(){
		if($(this).height() == 480)
		{
			$(this).animate({
				height:"440px"
			});
			$("#content").animate({
				height:"60"
			});
			$("#content_text").animate({
				opacity:"1"
			});
		}
		else
		{
			$(this).animate({
				height:"480"
			});
			$("#content").animate({
				height:"20"
			});
			$("#content_text").animate({
				opacity:"0"
			});
		}
		
	    });
});